Improves on asset_issue_handler.py
shotgunsoftware/sg-jira-bridge pull request #62
Opened 2023-07-11 16:23 UTC by carlos-villavicencio-adsk

Original work by @loney-liu

2023-07-11 20:12 UTC, carlos-villavicencio-adsk commented on tests/test_asset_hierarchy.py
> +            SHOTGUN_SYNC_IN_JIRA_FIELD: True,
The following tests are failing because of the new changes on asset_issue_handler.py. 

We need to review.

2023-07-13 17:01 UTC, NorberMV commented on examples/asset_hierarchy/asset_issue_handler.py
> +        """ "
I think we can remove the extra double quote on this docstring.

2023-07-13 17:07 UTC, NorberMV requested changes

2023-07-13 17:07 UTC, NorberMV commented on examples/asset_hierarchy/asset_issue_handler.py
> +        """ "
I think we can remove the extra double quote on this docstring.

2023-07-13 17:39 UTC, NorberMV approved these changes
LGTM !

2023-08-16 15:51 UTC, merged